accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r"^send_login_email$", views.send_login_email, name="send_login_email"),
    url(r"^login$", views.login, name="login"),
    url(r"^logout$", logout, {"next_page": "/"}, name="logout"),
]

babysfirstwords/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as accounts_urls


urlpatterns = [
    url(r"^$", list_views.home, name="home"),
    url(r"^lists/", include(list_urls)),
    url(r"^accounts/", include(accounts_urls)),
]

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r"^new$", views.new_list, name="new_list"),
    url(r"^(\d+)/$", views.view_list, name="view_list"),
    url(r"^(\d+)/share$", views.share_list, name="share_list"),
    url(r"^users/(.+)/$", views.my_lists, name="my_lists"),
]

accounts/models.py
import uuid
from django.contrib import auth
from django.db import models


auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="shares_list", blank=True)

    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])

    def __str__(self):
        return str(self.id)

    @property
    def name(self):
        return self.item_set.first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item, List


EMPTY_ITEM_ERROR = "You cannot have an empty list item"
DUPLICATE_ITEM_ERROR = "You already have this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.fields.TextInput(attrs={
                "placeholder": "Enter a word",
                "class": "form-control",
            }),
        }
        error_messages = {
            "text": {"required": EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib import auth, messages
from django.core.urlresolvers import reverse
from accounts.models import Token


def send_login_email(request):
    email = request.POST["email"]
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse("login") + "?token=" + str(token.uid)
    )
    message_body = "Use this link to log in:\n\n{}".format(url)

    send_mail(
        "Your login link for Baby's First Words",
        message_body,
        "noreply@babys-first-words",
        [email],
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect("/")


def login(request):
    user = auth.authenticate(uid=request.GET.get("token"))
    if user:
        auth.login(request, user)
    return redirect("/")

lists/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm


User = get_user_model()


def home(request):
    return render(request, "home.html", {"form": ItemForm()})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "list.html", {"list": list_, "form": form})


def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        email = request.POST.get("sharee", "")
        if email:
            try:
                sharee = User.objects.get(email=email)
            except User.DoesNotExist:
                sharee = User.objects.create(email=email)
            list_.shared_with.add(sharee)
        return redirect(list_)
    return render(request, "list.html", {"list": list_, "form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", {"owner": owner})

lists/templates/_nav.html
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand bfw-logo" href="{% url 'home' %}">Baby's First Words</a>
  <button class="navbar-toggler bfw-navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa fa-ellipsis-v"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a href="{% url 'home' %}" class="bfw-menu-link nav-link" alt="home">
                <i class="fa fa-home"></i>
                <span class="bfw-nav-label"> Home</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="bfw-menu-link nav-link" alt="about">
                <i class="fa fa-info"></i>
                <span class="bfw-nav-label"> About</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="bfw-menu-link nav-link" alt="contact">
                <i class="fa fa-envelope"></i>
                <span class="bfw-nav-label"> Contact</span>
            </a>
        </li>
    </ul>
    {% if user.email %}
        <a class="btn bfw-btn-outline-success my-2 my-sm-0 mr-2" href="{% url 'my_lists' user.email %}">My lists</a>
        <a id="id_logout" class="btn bfw-btn-outline-success my-2 my-sm-0" href="{% url 'logout' %}">Log out</a>
    {% else %}
        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'send_login_email' %}">
            <input id="login" class="form-control mr-sm-2" name="email" type="email" placeholder="Email" aria-label="Sign in"/>
            {% csrf_token %}
            <button class="btn bfw-btn-outline-success my-2 my-sm-0">Sign in</button>
        </form>
    {% endif %}
  </div>
</nav>

{% if user.email %}
    <div id="logged-in-as">Logged in as {{ user.email}}</div>
{% endif %}

lists/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An app to track your child's language development">
    <title>{% block title %}{% endblock %}Baby's First Words</title>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/_bfw-base.css">

    <!--<link rel="icon" type="image/png" href="static/img/logo-16x16.png" sizes="16x16">-->
    <!--<link rel="icon" type="image/png" href="static/img/logo-32x32.png" sizes="32x32">-->
    <!--<link rel="icon" type="image/png" href="static/img/logo-96x96.png" sizes="96x96">-->
</head>
<body>
{% include "_nav.html" %}
<div id="container">
    <div class="row">
        <div id="main" class="col">

            {% if messages %}
                <div class="row">
                    <div class="col-md-8">
                    {% for message in messages %}
                        {% if message.level_tag == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-warning">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="bfw-header">
                <h1>{% block header_text %}{% endblock %}</h1>
                <h2>{% block sub_header_text %}{% endblock %}</h2>
            </div>

            <div class="bfw-content-wrapper">
                <div class="bfw-content">
                    <div class="text-center">
                        {% block list_form %}
                            <form method="POST" action="{% block form_action %}{% endblock %}">
                                <div class="form-row align-items-center">
                                    <div class="col-sm-10">
                                        {{ form.text }}
                                    </div>
                                    {% csrf_token %}
                                    {% if form.errors %}
                                        <div class="form-group has-error">
                                            <div class="help-block">{{ form.text.errors }}</div>
                                        </div>
                                    {% endif %}
                                    <div class="col-sm-2">
                                        <button class="btn btn-primary">
                                            <i class="fa fa-paper-plane"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        {% endblock list_form %}
                        <div class="">
                            {% block table %}{% endblock %}
                        </div>

                        {% block extra_content %}{% endblock %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/jquery-3.2.1.min.js"></script>
<script src="https://use.fontawesome.com/4c28e24564.js"></script>
<script src="/static/js/list.js"></script>
<script>
$(document).ready(function () {
  window.babysFirstWords.initialize();
});
</script>
{% block scripts %}{% endblock %}

</body>
</html>

lists/templates/home.html
{% extends "base.html" %}

{% block title %}Home - {% endblock %}

{% block header_text %}Start a new list{% endblock %}
{% block sub_header_text %}Track your child's vocabulary as it develops{% endblock %}

{% block form_action %}{% url "new_list" %}{% endblock %}

lists/templates/list.html
{% extends "base.html" %}

{% block title %}Your words - {% endblock %}

{% block header_text %}Your words{% endblock %}

{% block form_action %}{% url "view_list" list.id %}{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}

{% block extra_content %}
    <div class="text-center">
        {% if list.shared_with.all %}
        <div class="">Shared with</div>
        <ul class="list-group">
            {% for user in list.shared_with.all %}
                <li class="list-group-item list-sharee">{{ user.email }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="">Share this list</div>
        <form method="POST" class="bfw-share-form" action ="{% url 'share_list' list.id %}">
            <div class="form-row align-items-center">
                <div class="col-sm-10">
                    <input id="sharee" class="form-control" name="sharee" type="email" placeholder="Email"/>
                </div>
                {% csrf_token %}
                <div class="col-sm-2">
                    <button class="btn btn-primary">
                        <i class="fa fa-share"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul class="list-group">
        {% for list in owner.list_set.all %}
            <li class="list-group-item">
                <a class="list-group-item-action" href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            </li>
        {% endfor %}
        {% for list in owner.shares_list.all %}
            <li class="list-group-item">
                <a class="list-group-item-action" href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}